### ISSUE TITLE
Matching *

### ISSUE THREAD

**Issue by lulupointu** [leonsenft/path_to_regexp#18]
Hi,

first thanks for the package it's great!

Maybe I'm doing something wrong but when I try to use an `*` in a route, I expect it to match everything but nothing is matched, the `*` is just escaped. Is this the expected behaviour?

I tried on your website
https://path-to-regexp.web.app/

And also trying the same on path-to-regexp in JavaScript, the `*` matches anything, as expected:
http://forbeslindesay.github.io/express-route-tester/

**Comment by leonsenft** [comment]
Hi @lulupointu!

> Maybe I'm doing something wrong but when I try to use an * in a route, I expect it to match everything but nothing is matched, the * is just escaped. Is this the expected behaviour?

This is expected behavior, there's no special matching for `*`.

I experimented with adding a special token for `*` quite awhile ago, but ultimately decided not to include it – the results are still on the https://github.com/leonsenft/path_to_regexp/tree/add-wildcard branch.

> And also trying the same on path-to-regexp in JavaScript, the * matches anything, as expected:

Older versions of it support it, but the later ones don't. If you change the package version to 2.0.0, you'll see that `*` no longer works that way. It looks like it was removed in that version: https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23

There are two problems or ambiguities I see with a match-all token like `*`:

1. How do you convert `*` to a path? In the branch linked above, I decided to treat it as an empty path, but it's not clear that would always be desired.
2. It doesn't introduce any new capability that I'm aware of. It's a slightly more convenient shorthand for writing the following path specification:

    ```dart
    pathToRegExp(':anything(.*)');
    ```

    I decided this minor convenience wasn't worth the implementation cost and ambiguity.

    And if the intent is to use it to match any suffix:

   ```dart
    pathToRegExp('/prefix/*');
   ```

   You can already accomplish this with prefix matching:

    ```dart
    pathToRegExp('/prefix', prefix: true);
    ```

If you have a strong motivating case otherwise, please let me know! Thank you!

**Comment by lulupointu** [comment]
I see your point ! 

Indeed my main issue is with the last case, since I'm writing a plugin and I don't want to add another attribute to remember (* feels so natural)!

I will definitely check the wildcard version since I think you interpretation is what I would expect. 
In any case I did find a workaround to enabling them but I think your implementation will be cleaner ;)

Thanks for taking the time to respond, and definitely thanks for this nice package!

**Comment by lulupointu** [comment]
After evaluation, I agree with you. Especially because of how powerful :_(.*) is. It enables to match as a prefix without using 'prefix=true'. So in the end the trade of this syntax complication vs the ambiguity does not seems so big anymore.

Thanks again for your time. I hope you will be able to appreciate my package as well when it is out :+1: !
